version: '3'

services:
    chdb:
        image: yandex/clickhouse-server
        volumes:
        - db-data:/var/lib/clickhouse
        - ./users.xml:/etc/clickhouse-server/users.xml
        - ./init.sql:/docker-entrypoint-initdb.d/init.sql
        ports:
            - 8123:8123
            - 9000:9000
            - 9009:9009
        ulimits:
            nproc: 65535
            nofile:
                soft: 262144
                hard: 262144
        hostname: "clickhouse-db"

volumes:
    db-data:
        driver: local
