version: '3'

services:
    postgre:
        image: postgres
        volumes:
            - pg-data:/var/lib/postgresql/data
            - ./pg_init.sql:/docker-entrypoint-initdb.d/init.sql
        ports:
            - 5432:5432
        environment:
            - POSTGRES_PASSWORD=mysecretpassword
            - POSTGRES_USER=postgres
            - POSTGRES_DB=base_prueba
        hostname: "postgresql-db"
        networks:
            mynetwork:
                ipv4_address:
                    157.162.0.25
    
    clickhouse:
        image: yandex/clickhouse-server
        volumes:
            - ch-data:/var/lib/clickhouse
            - ./users.xml:/etc/clickhouse-server/users.xml
            - ./ch_init.sql:/docker-entrypoint-initdb.d/init.sql
        ports:
            - 8123:8123
            - 9000:9000
            - 9009:9009
        ulimits:
            nproc: 65535
            nofile:
                soft: 262144
                hard: 262144
        hostname: "clickhouse-db"
        networks:
            mynetwork:
                ipv4_address:
                    157.162.0.12
    
    spark:
        image: javier/pyspark-notebook
        ports:
            - 8888:8888
        volumes:
            - notebooks:/home/jovyan/work
        networks:
            mynetwork:
                ipv4_address:
                    157.162.0.60
    
    pentaho:
        image: wmarinho/pentaho
        ports:
            - 8081:8080
        networks:
            mynetwork:
                ipv4_address:
                    157.162.0.80

volumes:
    pg-data:
        driver: local
    ch-data:
        driver: local
    notebooks:
        driver: local

networks:
    mynetwork:
        ipam:
            driver: default
            config:
                - subnet: "157.162.0.0/24"